# Generated by Django 4.2.6 on 2023-12-30 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bets',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 30, 23, 58, 47, 818739)),
        ),
    ]
