# Generated by Django 4.2.6 on 2023-12-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_alter_bets_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bets',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
