# Generated by Django 4.2.6 on 2023-10-23 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0003_game_draw_game_lose_game_win'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SportSection',
            new_name='Section',
        ),
        migrations.AlterModelOptions(
            name='section',
            options={},
        ),
    ]
