# Generated by Django 4.2.6 on 2023-11-19 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0005_game_members_game_point_game_time_game_tv'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('title_url', models.URLField()),
                ('image', models.ImageField(upload_to='image')),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='sport.section')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
