# Generated by Django 4.2.6 on 2023-12-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0008_player_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='image',
        ),
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(upload_to='%(team)s/%(name)s'),
        ),
    ]
