# Generated by Django 4.2.6 on 2023-12-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifyuser',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='users/'),
        ),
    ]
