# Generated by Django 4.2.6 on 2023-12-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_verifyuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifyuser',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
